server:
  port: 7417
spring:
  application:
    name: conig-server-1
  #配置微服务的配置仓库
  cloud:
    config:
      server:
#        native:
#          # 不指定路径的话，默认搜索 resources 目录
#          search-locations: C:/openspace/springcloud-config-server/config/
        git:
          #同config-server访问配置仓库的中配置的属性,以下是访问模式;
          #application:应用;profile:环境 label:git分支,默认master
          #/{application}/{profile}[/{label}]
          #/{application}-{profile}.yml
          #/{label}/{application}-{profile}.yml
          #/{application}-{profile}.properties
          #/{label}/{application}-{profile}.properties
          #例如:http://localhost:7417/abc-default.yml就可以查看配置的属性
          # {*}-{*}.[yml|propeties]
          #先按照匹配的去找,找不到,找默认例如applition.yml,前提是符合以上的模式,并且指定lable
          #
          uri: https://github.com/mynameiscuining/config-repo
          # 访问git仓库的用户名
          #spring.cloud.config.server.git.username=xxxxoooo
          # 访问git仓库的用户密码 如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写
          #spring.cloud.config.server.git.password=xxxxoooo



